// Frozen mainnet snapshot — generated by scripts/capture-fixture.mjs.
//
// DO NOT HAND-EDIT. Regenerate with `pnpm capture:fixture aquarius-concentrated`, then re-derive
// the expected values in adapters/snapshot.test.ts. If a factor moved, find out
// why before committing — that is the entire point of this file.
//
// Captured: 2026-08-29T09:36:02.586Z
// Not scored at capture time: this category publishes no weight table yet, so the adapter scoring methods throw by design. This fixture freezes the RAW SHAPE.
//
// `satisfies` is load-bearing: if AquariusRawData gains a required field, this file
// stops compiling rather than quietly feeding the adapter a stale shape.

import type { AquariusRawData } from '../../aquarius/index.ts';

export const aquariusConcentratedMainnet = {
  poolId: 'CA4HTZNY2RBZWEQE5GBMNREZMFRPAZSVJ6OGPC7T3VM7NHRJYFAVID2S',
  poolType: 'concentrated',
  tokens: [
    'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA',
    'CAUIKL3IYGMERDRUN6YSCLWVAKIFG5Q4YJHUKM4S4NJZQIA3BAS6OJPK',
  ],
  reserves: [4272366505631n, 3524317165205583n],
  totalShares: 11430750066584469n,
  feeFraction: 30,
  protocolFeeFraction: 5000,
  info: { fee: 30, pool_type: 'concentrated', tick_spacing: 60 },
  shareId: 'CA4HTZNY2RBZWEQE5GBMNREZMFRPAZSVJ6OGPC7T3VM7NHRJYFAVID2S',
  version: 200,
  killed: { swap: false, deposit: false, claim: false },
  emergencyMode: false,
  roles: {
    status: 'read',
    roles: [
      {
        role: 'Admin',
        addresses: ['GAV5FBMKD2ZF4X2MGWDNQYUP7KFL7MRM6HZBY7HKQLB4BRHSCCX5J6VS'],
        accounts: [
          {
            status: 'read',
            address: 'GAV5FBMKD2ZF4X2MGWDNQYUP7KFL7MRM6HZBY7HKQLB4BRHSCCX5J6VS',
            account: { highThreshold: 2, signerCount: 3, recentOps: 96, activityWindowDays: 30 },
          },
        ],
      },
      {
        role: 'EmergencyAdmin',
        addresses: ['GCGZ6E5RBUKLNB4VZ5RC65C4QMBSBJ3COVRRJCWAMCXJC36LB7YYWEKM'],
        accounts: [
          {
            status: 'read',
            address: 'GCGZ6E5RBUKLNB4VZ5RC65C4QMBSBJ3COVRRJCWAMCXJC36LB7YYWEKM',
            account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
          },
        ],
      },
      {
        role: 'EmergencyPauseAdmin',
        addresses: ['GA6MVTGQDCJPP27IAMG6PSDTWOJYTD3NUTLR2W54ADBCBY7OID5YUDSI'],
        accounts: [
          {
            status: 'read',
            address: 'GA6MVTGQDCJPP27IAMG6PSDTWOJYTD3NUTLR2W54ADBCBY7OID5YUDSI',
            account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
          },
        ],
      },
      {
        role: 'OperationsAdmin',
        addresses: ['GBVQPX2LQ55HLRMLIWBEYVVQL3SZ5RFPRKYLRSLZU4XRIWAXW2KQIMMD'],
        accounts: [
          {
            status: 'read',
            address: 'GBVQPX2LQ55HLRMLIWBEYVVQL3SZ5RFPRKYLRSLZU4XRIWAXW2KQIMMD',
            account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
          },
        ],
      },
      {
        role: 'PauseAdmin',
        addresses: ['GA6MA665XVKHTQUZVSMUKUPGT7OREJNCLAZ5ZEH5CXPKYTWFJKZ3YSEK'],
        accounts: [
          {
            status: 'read',
            address: 'GA6MA665XVKHTQUZVSMUKUPGT7OREJNCLAZ5ZEH5CXPKYTWFJKZ3YSEK',
            account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
          },
        ],
      },
      {
        role: 'RewardsAdmin',
        addresses: ['GCXYKA3BM574WC6TWESEDUGUJTNQ5SVCFMHWLQ634H5FTE7FYPV3JH3X'],
        accounts: [
          {
            status: 'read',
            address: 'GCXYKA3BM574WC6TWESEDUGUJTNQ5SVCFMHWLQ634H5FTE7FYPV3JH3X',
            account: { highThreshold: 0, signerCount: 1, recentOps: 200, activityWindowDays: 30 },
          },
        ],
      },
      {
        role: 'SystemFeeAdmin',
        addresses: ['GB57YDVGLL2BAVOXHPXYCZR77J4MLPLMGJKFMTUKMHFI2AEGS4SGGW7N'],
        accounts: [
          {
            status: 'read',
            address: 'GB57YDVGLL2BAVOXHPXYCZR77J4MLPLMGJKFMTUKMHFI2AEGS4SGGW7N',
            account: { highThreshold: 0, signerCount: 1, recentOps: 200, activityWindowDays: 30 },
          },
        ],
      },
    ],
  },
  upgrade: {
    deadline: 0n,
    futureWasm: '12fca5a7a96577273b6d4184cf9c984036cda0e8f0594747e7b2933dced37ee6',
    runningWasm: '12fca5a7a96577273b6d4184cf9c984036cda0e8f0594747e7b2933dced37ee6',
    pending: false,
    stagedDiffers: false,
  },
  reserveTokens: [
    {
      address: 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA',
      isStellarAsset: true,
      code: 'XLM',
      decimals: 7,
      symbol: 'native',
      issuer: { status: 'noIssuer', asset: 'native' },
    },
    {
      address: 'CAUIKL3IYGMERDRUN6YSCLWVAKIFG5Q4YJHUKM4S4NJZQIA3BAS6OJPK',
      isStellarAsset: true,
      code: 'AQUA',
      decimals: 7,
      symbol: 'AQUA',
      issuer: {
        status: 'read',
        issuer: 'GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA',
        flags: {
          authRequired: false,
          authRevocable: false,
          authImmutable: false,
          authClawbackEnabled: false,
        },
      },
    },
  ],
  router: {
    routerId: 'CBQDHNBFBZYE4MKPWBSJOPIYLW4SFSXAXUTSXJN76GNKYVYPCKWC6QUK',
    contractName: 'AMMRouter',
    version: 200,
    emergencyMode: false,
    roles: {
      status: 'read',
      roles: [
        {
          role: 'Admin',
          addresses: ['GAV5FBMKD2ZF4X2MGWDNQYUP7KFL7MRM6HZBY7HKQLB4BRHSCCX5J6VS'],
          accounts: [
            {
              status: 'read',
              address: 'GAV5FBMKD2ZF4X2MGWDNQYUP7KFL7MRM6HZBY7HKQLB4BRHSCCX5J6VS',
              account: { highThreshold: 2, signerCount: 3, recentOps: 96, activityWindowDays: 30 },
            },
          ],
        },
        {
          role: 'EmergencyAdmin',
          addresses: ['GCGZ6E5RBUKLNB4VZ5RC65C4QMBSBJ3COVRRJCWAMCXJC36LB7YYWEKM'],
          accounts: [
            {
              status: 'read',
              address: 'GCGZ6E5RBUKLNB4VZ5RC65C4QMBSBJ3COVRRJCWAMCXJC36LB7YYWEKM',
              account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
            },
          ],
        },
        {
          role: 'EmergencyPauseAdmin',
          addresses: ['GA6MVTGQDCJPP27IAMG6PSDTWOJYTD3NUTLR2W54ADBCBY7OID5YUDSI'],
          accounts: [
            {
              status: 'read',
              address: 'GA6MVTGQDCJPP27IAMG6PSDTWOJYTD3NUTLR2W54ADBCBY7OID5YUDSI',
              account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
            },
          ],
        },
        {
          role: 'OperationsAdmin',
          addresses: ['GBVQPX2LQ55HLRMLIWBEYVVQL3SZ5RFPRKYLRSLZU4XRIWAXW2KQIMMD'],
          accounts: [
            {
              status: 'read',
              address: 'GBVQPX2LQ55HLRMLIWBEYVVQL3SZ5RFPRKYLRSLZU4XRIWAXW2KQIMMD',
              account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
            },
          ],
        },
        {
          role: 'PauseAdmin',
          addresses: ['GA6MA665XVKHTQUZVSMUKUPGT7OREJNCLAZ5ZEH5CXPKYTWFJKZ3YSEK'],
          accounts: [
            {
              status: 'read',
              address: 'GA6MA665XVKHTQUZVSMUKUPGT7OREJNCLAZ5ZEH5CXPKYTWFJKZ3YSEK',
              account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
            },
          ],
        },
        {
          role: 'RewardsAdmin',
          addresses: ['GCXYKA3BM574WC6TWESEDUGUJTNQ5SVCFMHWLQ634H5FTE7FYPV3JH3X'],
          accounts: [
            {
              status: 'read',
              address: 'GCXYKA3BM574WC6TWESEDUGUJTNQ5SVCFMHWLQ634H5FTE7FYPV3JH3X',
              account: { highThreshold: 0, signerCount: 1, recentOps: 200, activityWindowDays: 30 },
            },
          ],
        },
        {
          role: 'SystemFeeAdmin',
          addresses: ['GB57YDVGLL2BAVOXHPXYCZR77J4MLPLMGJKFMTUKMHFI2AEGS4SGGW7N'],
          accounts: [
            {
              status: 'read',
              address: 'GB57YDVGLL2BAVOXHPXYCZR77J4MLPLMGJKFMTUKMHFI2AEGS4SGGW7N',
              account: { highThreshold: 0, signerCount: 1, recentOps: 200, activityWindowDays: 30 },
            },
          ],
        },
      ],
    },
    upgrade: {
      deadline: 0n,
      futureWasm: '06f4207b0c9ef78cc595e075ded8fa40e73fdb8346e5f9281068a2d4ba1e5037',
      runningWasm: '06f4207b0c9ef78cc595e075ded8fa40e73fdb8346e5f9281068a2d4ba1e5037',
      pending: false,
      stagedDiffers: false,
    },
  },
  fetchedAt: 1787996162,
} satisfies AquariusRawData;
