// Frozen mainnet snapshot — generated by scripts/capture-fixture.mjs.
//
// DO NOT HAND-EDIT. Regenerate with `pnpm capture:fixture aquarius-wasm-token`, then re-derive
// the expected values in adapters/snapshot.test.ts. If a factor moved, find out
// why before committing — that is the entire point of this file.
//
// Captured: 2026-08-29T09:36:10.809Z
// Not scored at capture time: this category publishes no weight table yet, so the adapter scoring methods throw by design. This fixture freezes the RAW SHAPE.
//
// `satisfies` is load-bearing: if AquariusRawData gains a required field, this file
// stops compiling rather than quietly feeding the adapter a stale shape.

import type { AquariusRawData } from '../../aquarius/index.ts';

export const aquariusWasmTokenMainnet = {
  poolId: 'CA262ONRV6P2IZPFVCTQNIU5XZIPZE4RLZNSOVJUNFUWDQR6MBNKS3IB',
  poolType: 'stable',
  tokens: [
    'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75',
    'CDPV3H7C3MR2R4Y4GAEJN4AXXY4LBITRRVE74VSMVCSBWISIU3Q4QTMW',
  ],
  reserves: [4072255n, 407328n],
  totalShares: 8144723n,
  feeFraction: 10,
  protocolFeeFraction: 5000,
  info: { a: 1500n, fee: 10, n_tokens: 2, pool_type: 'stable' },
  shareId: 'CCICZJOZMAKZOPAQ5W4BQE4557WF43XF4YI4BRTR6GCWRLURSABTMVA6',
  version: 200,
  killed: { swap: false, deposit: false, claim: false },
  emergencyMode: false,
  roles: {
    status: 'read',
    roles: [
      {
        role: 'Admin',
        addresses: ['GAV5FBMKD2ZF4X2MGWDNQYUP7KFL7MRM6HZBY7HKQLB4BRHSCCX5J6VS'],
        accounts: [
          {
            status: 'read',
            address: 'GAV5FBMKD2ZF4X2MGWDNQYUP7KFL7MRM6HZBY7HKQLB4BRHSCCX5J6VS',
            account: { highThreshold: 2, signerCount: 3, recentOps: 96, activityWindowDays: 30 },
          },
        ],
      },
      {
        role: 'EmergencyAdmin',
        addresses: ['GCGZ6E5RBUKLNB4VZ5RC65C4QMBSBJ3COVRRJCWAMCXJC36LB7YYWEKM'],
        accounts: [
          {
            status: 'read',
            address: 'GCGZ6E5RBUKLNB4VZ5RC65C4QMBSBJ3COVRRJCWAMCXJC36LB7YYWEKM',
            account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
          },
        ],
      },
      {
        role: 'EmergencyPauseAdmin',
        addresses: ['GA6MVTGQDCJPP27IAMG6PSDTWOJYTD3NUTLR2W54ADBCBY7OID5YUDSI'],
        accounts: [
          {
            status: 'read',
            address: 'GA6MVTGQDCJPP27IAMG6PSDTWOJYTD3NUTLR2W54ADBCBY7OID5YUDSI',
            account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
          },
        ],
      },
      {
        role: 'OperationsAdmin',
        addresses: ['GBVQPX2LQ55HLRMLIWBEYVVQL3SZ5RFPRKYLRSLZU4XRIWAXW2KQIMMD'],
        accounts: [
          {
            status: 'read',
            address: 'GBVQPX2LQ55HLRMLIWBEYVVQL3SZ5RFPRKYLRSLZU4XRIWAXW2KQIMMD',
            account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
          },
        ],
      },
      {
        role: 'PauseAdmin',
        addresses: ['GA6MA665XVKHTQUZVSMUKUPGT7OREJNCLAZ5ZEH5CXPKYTWFJKZ3YSEK'],
        accounts: [
          {
            status: 'read',
            address: 'GA6MA665XVKHTQUZVSMUKUPGT7OREJNCLAZ5ZEH5CXPKYTWFJKZ3YSEK',
            account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
          },
        ],
      },
      {
        role: 'RewardsAdmin',
        addresses: ['GCXYKA3BM574WC6TWESEDUGUJTNQ5SVCFMHWLQ634H5FTE7FYPV3JH3X'],
        accounts: [
          {
            status: 'read',
            address: 'GCXYKA3BM574WC6TWESEDUGUJTNQ5SVCFMHWLQ634H5FTE7FYPV3JH3X',
            account: { highThreshold: 0, signerCount: 1, recentOps: 200, activityWindowDays: 30 },
          },
        ],
      },
      {
        role: 'SystemFeeAdmin',
        addresses: ['GB57YDVGLL2BAVOXHPXYCZR77J4MLPLMGJKFMTUKMHFI2AEGS4SGGW7N'],
        accounts: [
          {
            status: 'read',
            address: 'GB57YDVGLL2BAVOXHPXYCZR77J4MLPLMGJKFMTUKMHFI2AEGS4SGGW7N',
            account: { highThreshold: 0, signerCount: 1, recentOps: 200, activityWindowDays: 30 },
          },
        ],
      },
    ],
  },
  upgrade: {
    deadline: 0n,
    futureWasm: 'f1077e0b77da5e62d596e13aeae4160104cad99e7ef7f3183a6c9b6ec9e747cd',
    runningWasm: 'f1077e0b77da5e62d596e13aeae4160104cad99e7ef7f3183a6c9b6ec9e747cd',
    pending: false,
    stagedDiffers: false,
  },
  reserveTokens: [
    {
      address: 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75',
      isStellarAsset: true,
      code: 'USDC',
      decimals: 7,
      symbol: 'USDC',
      issuer: {
        status: 'read',
        issuer: 'GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN',
        flags: {
          authRequired: false,
          authRevocable: true,
          authImmutable: false,
          authClawbackEnabled: false,
        },
      },
    },
    {
      address: 'CDPV3H7C3MR2R4Y4GAEJN4AXXY4LBITRRVE74VSMVCSBWISIU3Q4QTMW',
      isStellarAsset: false,
      code: 'USDC',
      decimals: 6,
      symbol: 'USDC',
      issuer: { status: 'notApplicable', reason: 'wasm-contract' },
    },
  ],
  router: {
    routerId: 'CBQDHNBFBZYE4MKPWBSJOPIYLW4SFSXAXUTSXJN76GNKYVYPCKWC6QUK',
    contractName: 'AMMRouter',
    version: 200,
    emergencyMode: false,
    roles: {
      status: 'read',
      roles: [
        {
          role: 'Admin',
          addresses: ['GAV5FBMKD2ZF4X2MGWDNQYUP7KFL7MRM6HZBY7HKQLB4BRHSCCX5J6VS'],
          accounts: [
            {
              status: 'read',
              address: 'GAV5FBMKD2ZF4X2MGWDNQYUP7KFL7MRM6HZBY7HKQLB4BRHSCCX5J6VS',
              account: { highThreshold: 2, signerCount: 3, recentOps: 96, activityWindowDays: 30 },
            },
          ],
        },
        {
          role: 'EmergencyAdmin',
          addresses: ['GCGZ6E5RBUKLNB4VZ5RC65C4QMBSBJ3COVRRJCWAMCXJC36LB7YYWEKM'],
          accounts: [
            {
              status: 'read',
              address: 'GCGZ6E5RBUKLNB4VZ5RC65C4QMBSBJ3COVRRJCWAMCXJC36LB7YYWEKM',
              account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
            },
          ],
        },
        {
          role: 'EmergencyPauseAdmin',
          addresses: ['GA6MVTGQDCJPP27IAMG6PSDTWOJYTD3NUTLR2W54ADBCBY7OID5YUDSI'],
          accounts: [
            {
              status: 'read',
              address: 'GA6MVTGQDCJPP27IAMG6PSDTWOJYTD3NUTLR2W54ADBCBY7OID5YUDSI',
              account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
            },
          ],
        },
        {
          role: 'OperationsAdmin',
          addresses: ['GBVQPX2LQ55HLRMLIWBEYVVQL3SZ5RFPRKYLRSLZU4XRIWAXW2KQIMMD'],
          accounts: [
            {
              status: 'read',
              address: 'GBVQPX2LQ55HLRMLIWBEYVVQL3SZ5RFPRKYLRSLZU4XRIWAXW2KQIMMD',
              account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
            },
          ],
        },
        {
          role: 'PauseAdmin',
          addresses: ['GA6MA665XVKHTQUZVSMUKUPGT7OREJNCLAZ5ZEH5CXPKYTWFJKZ3YSEK'],
          accounts: [
            {
              status: 'read',
              address: 'GA6MA665XVKHTQUZVSMUKUPGT7OREJNCLAZ5ZEH5CXPKYTWFJKZ3YSEK',
              account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
            },
          ],
        },
        {
          role: 'RewardsAdmin',
          addresses: ['GCXYKA3BM574WC6TWESEDUGUJTNQ5SVCFMHWLQ634H5FTE7FYPV3JH3X'],
          accounts: [
            {
              status: 'read',
              address: 'GCXYKA3BM574WC6TWESEDUGUJTNQ5SVCFMHWLQ634H5FTE7FYPV3JH3X',
              account: { highThreshold: 0, signerCount: 1, recentOps: 200, activityWindowDays: 30 },
            },
          ],
        },
        {
          role: 'SystemFeeAdmin',
          addresses: ['GB57YDVGLL2BAVOXHPXYCZR77J4MLPLMGJKFMTUKMHFI2AEGS4SGGW7N'],
          accounts: [
            {
              status: 'read',
              address: 'GB57YDVGLL2BAVOXHPXYCZR77J4MLPLMGJKFMTUKMHFI2AEGS4SGGW7N',
              account: { highThreshold: 0, signerCount: 1, recentOps: 200, activityWindowDays: 30 },
            },
          ],
        },
      ],
    },
    upgrade: {
      deadline: 0n,
      futureWasm: '06f4207b0c9ef78cc595e075ded8fa40e73fdb8346e5f9281068a2d4ba1e5037',
      runningWasm: '06f4207b0c9ef78cc595e075ded8fa40e73fdb8346e5f9281068a2d4ba1e5037',
      pending: false,
      stagedDiffers: false,
    },
  },
  fetchedAt: 1787996170,
} satisfies AquariusRawData;
