// Frozen mainnet snapshot — generated by scripts/capture-fixture.mjs.
//
// DO NOT HAND-EDIT. Regenerate with `pnpm capture:fixture blend`, then re-derive
// the expected values in adapters/snapshot.test.ts. If a factor moved, find out
// why before committing — that is the entire point of this file.
//
// Captured: 2026-08-18T12:18:53.305Z
// At capture time this scored: safetyScore 54 (collateralSafety 71, oracleSafety 100, adminKeySafety 40, liquiditySafety 23, utilizationSafety 15)
//
// `satisfies` is load-bearing: if BlendRawData gains a required field, this file
// stops compiling rather than quietly feeding the adapter a stale shape.

import type { BlendRawData } from '../blend/index.ts';

export const blendMainnet = {
  poolId: 'CAJJZSGMMM3PD7N33TAPHGBUGTB43OC73HVIK2L2G6BNGGGYOSSYBXBD',
  oracleId: 'CCVTVW2CVA7JLH4ROQGP3CU4T3EXVCK66AZGSM4MUQPXAI4QHCZPOATS',
  oracleDecimals: 7,
  status: 1,
  minCollateral: 50000000n,
  admin: {
    address: 'GAX2VVWVHU5YQY5J3NJBXKHI3FFKZN54BE6GRJCWSIKSBZTQWJJNJMPC',
    isContract: false,
    account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
  },
  oracleConfig: {
    maxAge: 900,
    baseAssets: [],
    oracles: [
      {
        index: 0,
        address: 'CAFJZQWSED6YAWZU3GWRTOCNPPCGBN32L7QV43XX5LZLFTK6JLN34DLN',
        resolution: 300,
        decimals: 14,
      },
    ],
  },
  reserves: [
    {
      asset: 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA',
      config: {
        decimals: 7,
        cFactor: 7500000n,
        lFactor: 7500000n,
        util: 4000000n,
        maxUtil: 7000000n,
        enabled: true,
      },
      data: {
        dRate: 1001520650764n,
        bRate: 1000022236789n,
        bSupply: 7685718879420512n,
        dSupply: 14277657918510n,
      },
      price: { value: 1532003n, timestamp: 1787055300 },
      priceConfig: { upstreamAsset: 'Other:XLM', oracleIndex: 0, maxDev: 60 },
    },
    {
      asset: 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75',
      config: {
        decimals: 7,
        cFactor: 9500000n,
        lFactor: 9500000n,
        util: 8000000n,
        maxUtil: 9000000n,
        enabled: true,
      },
      data: {
        dRate: 1222104480312n,
        bRate: 1139610716797n,
        bSupply: 563890003175335n,
        dSupply: 402284022286888n,
      },
      price: { value: 10008876n, timestamp: 1787055300 },
      priceConfig: { upstreamAsset: 'Other:USDC', oracleIndex: 0, maxDev: 20 },
    },
    {
      asset: 'CDTKPWPLOURQA2SGTKTUQOWRCBZEORB4BWBOMJ3D3ZTQQSGE5F6JBQLV',
      config: {
        decimals: 7,
        cFactor: 9500000n,
        lFactor: 9500000n,
        util: 8000000n,
        maxUtil: 9000000n,
        enabled: true,
      },
      data: {
        dRate: 1225442373158n,
        bRate: 1140682362932n,
        bSupply: 25825898186705n,
        dSupply: 17997536239877n,
      },
      price: { value: 11588012n, timestamp: 1787055300 },
      priceConfig: { upstreamAsset: 'Other:EURC', oracleIndex: 0, maxDev: 20 },
    },
  ],
  fetchedAt: 1787055533,
} satisfies BlendRawData;
