// Frozen mainnet snapshot — generated by scripts/capture-fixture.mjs.
//
// DO NOT HAND-EDIT. Regenerate with `pnpm capture:fixture blend`, then re-derive
// the expected values in adapters/snapshot.test.ts. If a factor moved, find out
// why before committing — that is the entire point of this file.
//
// Captured: 2026-08-16T12:24:30.039Z
// At capture time this scored: safetyScore 53 (collateralSafety 70, oracleSafety 100, adminKeySafety 40, liquiditySafety 21, utilizationSafety 12)
//
// `satisfies` is load-bearing: if BlendRawData gains a required field, this file
// stops compiling rather than quietly feeding the adapter a stale shape.

import type { BlendRawData } from '../blend.ts';

export const blendMainnet = {
  poolId: 'CAJJZSGMMM3PD7N33TAPHGBUGTB43OC73HVIK2L2G6BNGGGYOSSYBXBD',
  oracleId: 'CCVTVW2CVA7JLH4ROQGP3CU4T3EXVCK66AZGSM4MUQPXAI4QHCZPOATS',
  oracleDecimals: 7,
  status: 1,
  admin: {
    address: 'GAX2VVWVHU5YQY5J3NJBXKHI3FFKZN54BE6GRJCWSIKSBZTQWJJNJMPC',
    isContract: false,
    account: { highThreshold: 0, signerCount: 1, recentOps: 0, activityWindowDays: 30 },
  },
  oracleConfig: {
    maxAge: 900,
    baseAssets: [],
    oracles: [
      {
        index: 0,
        address: 'CAFJZQWSED6YAWZU3GWRTOCNPPCGBN32L7QV43XX5LZLFTK6JLN34DLN',
        resolution: 300,
        decimals: 14,
      },
    ],
  },
  reserves: [
    {
      asset: 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA',
      config: {
        decimals: 7,
        cFactor: 7500000n,
        lFactor: 7500000n,
        util: 4000000n,
        maxUtil: 7000000n,
        enabled: true,
      },
      data: {
        dRate: 1001515118894n,
        bRate: 1000022228606n,
        bSupply: 7686167566738108n,
        dSupply: 14298726642175n,
      },
      price: { value: 1568646n, timestamp: 1786882800 },
      priceConfig: { upstreamAsset: 'Other:XLM', oracleIndex: 0, maxDev: 60 },
    },
    {
      asset: 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75',
      config: {
        decimals: 7,
        cFactor: 9500000n,
        lFactor: 9500000n,
        util: 8000000n,
        maxUtil: 9000000n,
        enabled: true,
      },
      data: {
        dRate: 1221403469415n,
        bRate: 1139207224686n,
        bSupply: 545615708615427n,
        dSupply: 402252761629576n,
      },
      price: { value: 10009204n, timestamp: 1786882800 },
      priceConfig: { upstreamAsset: 'Other:USDC', oracleIndex: 0, maxDev: 20 },
    },
    {
      asset: 'CDTKPWPLOURQA2SGTKTUQOWRCBZEORB4BWBOMJ3D3ZTQQSGE5F6JBQLV',
      config: {
        decimals: 7,
        cFactor: 9500000n,
        lFactor: 9500000n,
        util: 8000000n,
        maxUtil: 9000000n,
        enabled: true,
      },
      data: {
        dRate: 1224916473552n,
        bRate: 1140389770338n,
        bSupply: 25619578866528n,
        dSupply: 17805748874511n,
      },
      price: { value: 11575207n, timestamp: 1786882800 },
      priceConfig: { upstreamAsset: 'Other:EURC', oracleIndex: 0, maxDev: 20 },
    },
  ],
  fetchedAt: 1786883070,
} satisfies BlendRawData;
