// Frozen mainnet snapshot — generated by scripts/capture-fixture.mjs.
//
// DO NOT HAND-EDIT. Regenerate with `pnpm capture:fixture etherfuse`, then re-derive
// the expected values in adapters/snapshot.test.ts. If a factor moved, find out
// why before committing — that is the entire point of this file.
//
// Captured: 2026-08-26T09:49:03.062Z
// At capture time this scored: safetyScore 50 (collateralSafety 94, oracleSafety 100, adminKeySafety 10, liquiditySafety 16, utilizationSafety 11)
//
// `satisfies` is load-bearing: if BlendRawData gains a required field, this file
// stops compiling rather than quietly feeding the adapter a stale shape.

import type { BlendRawData } from '../blend/index.ts';

export const etherfuseMainnet = {
  poolId: 'CDMAVJPFXPADND3YRL4BSM3AKZWCTFMX27GLLXCML3PD62HEQS5FPVAI',
  oracleId: 'CAVRP26CWW6IUEXBRA3Q2T2SHBUVBC2DF43M4E23LEZGW5ZEIB62HALS',
  oracleDecimals: 14,
  status: 1,
  minCollateral: 500000000000000n,
  admin: {
    address: 'GDH3FRHOOWXYXEASH43N2VOVFOPJSVJF3EQFSLBLJYFPHOUAF4N4AETH',
    isContract: false,
    account: { highThreshold: 0, signerCount: 1, recentOps: 200, activityWindowDays: 30 },
  },
  oracleConfig: {
    maxAge: 600,
    baseAssets: [],
    oracles: [
      {
        index: 0,
        address: 'CBWUSO5XZICR4FPKAQ4YDIYNZ2T26QMKUHWOSMPMWTXHFP3SJTAXGNCK',
        resolution: 300,
        decimals: 14,
      },
      {
        index: 1,
        address: 'CAFJZQWSED6YAWZU3GWRTOCNPPCGBN32L7QV43XX5LZLFTK6JLN34DLN',
        resolution: 300,
        decimals: 14,
      },
    ],
  },
  reserves: [
    {
      asset: 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA',
      config: {
        decimals: 7,
        cFactor: 7500000n,
        lFactor: 7500000n,
        util: 5000000n,
        maxUtil: 7000000n,
        enabled: true,
      },
      data: {
        dRate: 1002278906802n,
        bRate: 1000398875897n,
        bSupply: 503124751765n,
        dSupply: 34242346409n,
      },
      price: { value: 18227347524946n, timestamp: 1787737500 },
      priceConfig: { upstreamAsset: 'Other:XLM', oracleIndex: 1, maxDev: 10 },
    },
    {
      asset: 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75',
      config: {
        decimals: 7,
        cFactor: 9500000n,
        lFactor: 9500000n,
        util: 8000000n,
        maxUtil: 9500000n,
        enabled: true,
      },
      data: {
        dRate: 1024183405306n,
        bRate: 1016354564978n,
        bSupply: 231840701052n,
        dSupply: 194047315118n,
      },
      price: { value: 100010001000100n, timestamp: 1787737500 },
      priceConfig: { upstreamAsset: 'Other:USDC', oracleIndex: 1, maxDev: 5 },
    },
    {
      asset: 'CAL6ER2TI6CTRAY6BFXWNWA7WTYXUXTQCHUBCIBU5O6KM3HJFG6Z6VXV',
      config: {
        decimals: 7,
        cFactor: 8000000n,
        lFactor: 8000000n,
        util: 5000000n,
        maxUtil: 9000000n,
        enabled: true,
      },
      data: {
        dRate: 1005406025965n,
        bRate: 1002918462143n,
        bSupply: 7181049045300n,
        dSupply: 233890520n,
      },
      price: { value: 6954377003599n, timestamp: 1787737500 },
      priceConfig: {
        upstreamAsset: 'Stellar:CAL6ER2TI6CTRAY6BFXWNWA7WTYXUXTQCHUBCIBU5O6KM3HJFG6Z6VXV',
        oracleIndex: 0,
        maxDev: 5,
      },
    },
    {
      asset: 'CBLV4ATSIWU67CFSQU2NVRKINQIKUZ2ODSZBUJTJ43VJVRSBTZYOPNUR',
      config: {
        decimals: 7,
        cFactor: 9000000n,
        lFactor: 9000000n,
        util: 5000000n,
        maxUtil: 9000000n,
        enabled: true,
      },
      data: {
        dRate: 1010796831249n,
        bRate: 1004813796541n,
        bSupply: 210772415983n,
        dSupply: 59407196860n,
      },
      price: { value: 107303400000000n, timestamp: 1787737500 },
      priceConfig: {
        upstreamAsset: 'Stellar:CBLV4ATSIWU67CFSQU2NVRKINQIKUZ2ODSZBUJTJ43VJVRSBTZYOPNUR',
        oracleIndex: 0,
        maxDev: 5,
      },
    },
    {
      asset: 'CD6M4R2322BYCY2LNWM74PEBQAQ63SA3DUJLI3L4225U4ZVCLMSCBCIS',
      config: {
        decimals: 7,
        cFactor: 8000000n,
        lFactor: 8000000n,
        util: 5000000n,
        maxUtil: 9000000n,
        enabled: true,
      },
      data: {
        dRate: 1011885499613n,
        bRate: 1005123509910n,
        bSupply: 1149432503729n,
        dSupply: 503046609997n,
      },
      price: { value: 24180537294265n, timestamp: 1787737500 },
      priceConfig: {
        upstreamAsset: 'Stellar:CD6M4R2322BYCY2LNWM74PEBQAQ63SA3DUJLI3L4225U4ZVCLMSCBCIS',
        oracleIndex: 0,
        maxDev: 5,
      },
    },
  ],
  fetchedAt: 1787737743,
} satisfies BlendRawData;
