// Frozen mainnet snapshot — generated by scripts/capture-fixture.mjs.
//
// DO NOT HAND-EDIT. Regenerate with `pnpm capture:fixture kinetic`, then re-derive
// the expected values in adapters/snapshot.test.ts. If a factor moved, find out
// why before committing — that is the entire point of this file.
//
// ONE HAND-EDITED FIELD, and this is the record of it. `KineticReserveRaw` gained
// a required `flags` block on 2026-08-25 (issue #15, per-reserve gating state).
// This fixture was NOT regenerated to absorb it — snapshot.test.ts explains why
// at length: it is the only captured state in which the pre-minimum-size-filter
// defect is visible, and a re-capture would have destroyed that evidence for an
// unrelated shape change. So the four `flags` blocks below were added by hand,
// and they are the ONLY values in this file that are not part of the
// 2026-08-16 capture: they were read from the same four reserves on
// 2026-08-25 (all four active, unfrozen, borrowable, unpaused) and are labelled
// here rather than passed off as part of the snapshot. Nothing asserts on them —
// the pause tests run against synthetic fixtures, which is where a flag
// combination should be chosen deliberately rather than inherited from whatever
// the chain happened to say.
//
// Everything else here IS the frozen 2026-08-16 capture. Regenerate the rest only
// by reading snapshot.test.ts first.
//
// Captured: 2026-08-16T12:24:41.773Z
// At capture time this scored: safetyScore 24 (collateralSafety 15, oracleSafety 0, adminKeySafety 60, liquiditySafety 34, utilizationSafety 18)
//
// `satisfies` is load-bearing: if KineticRawData gains a required field, this file
// stops compiling rather than quietly feeding the adapter a stale shape.

import type { KineticRawData } from '../kinetic/index.ts';

export const kineticMainnet = {
  routerId: 'CCTUJZLYFAW7ZNQD2SXMUZIHBUUJJICYRKWLZJ6SK6TGNAWNXOJIV6J7',
  oracleId: 'CCHRZE2K5TCERZLDO5IXDUWUKLRPVE72DI3TDF2RP6EQKEW6BNOMQRMU',
  oraclePriceDecimals: 14,
  paused: false,
  admin: {
    address: 'CC4UQND4XSP5MBHYOKGGJZQRONSTSJ3OF2EPEGA5QMCDCCZFLAE43BWJ',
    isContract: true,
    account: null,
  },
  oracleConfig: {
    maxPriceChangeBps: 2000,
    priceStalenessThreshold: 3600,
    priceCacheTtl: 30,
    paused: false,
  },
  reserves: [
    {
      asset: 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75',
      decimals: 7,
      flags: { active: true, frozen: false, borrowingEnabled: true, paused: false },
      suppliedRaw: 539974427n,
      borrowedRaw: 50016738n,
      price: { value: 99981899000000n, timestamp: 1786880550 },
      priceConfig: {
        enabled: true,
        maxAge: 86400,
        source: 'batchAdapter',
        feedId: 'USDC',
        manualOverrideActive: false,
        breakerBaseline: 99976950000000n,
      },
    },
    {
      asset: 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA',
      decimals: 7,
      flags: { active: true, frozen: false, borrowingEnabled: true, paused: false },
      suppliedRaw: 94187156666n,
      borrowedRaw: 394246737n,
      price: { value: 15697547000000n, timestamp: 1786878850 },
      priceConfig: {
        enabled: true,
        maxAge: 43200,
        source: 'batchAdapter',
        feedId: 'XLM',
        manualOverrideActive: false,
        breakerBaseline: 15674310000000n,
      },
    },
    {
      asset: 'CCCRWH6Q3FNP3I2I57BDLM5AFAT7O6OF6GKQOC6SSJNDAVRZ57SPHGU2',
      decimals: 7,
      flags: { active: true, frozen: false, borrowingEnabled: true, paused: false },
      suppliedRaw: 30025859n,
      borrowedRaw: 19751205n,
      price: { value: 99949950000000n, timestamp: 1786880590 },
      priceConfig: {
        enabled: true,
        maxAge: 86400,
        source: 'batchAdapter',
        feedId: 'PYUSD',
        manualOverrideActive: false,
        breakerBaseline: 99936997000000n,
      },
    },
    {
      asset: 'CBIJBDNZNF4X35BJ4FFZWCDBSCKOP5NB4PLG4SNENRMLAPYG4P5FM6VN',
      decimals: 8,
      flags: { active: true, frozen: false, borrowingEnabled: true, paused: false },
      suppliedRaw: 56681n,
      borrowedRaw: 31663n,
      price: { value: 6313844882710000000n, timestamp: 1786882510 },
      priceConfig: {
        enabled: true,
        maxAge: 43200,
        source: 'batchAdapter',
        feedId: 'SolvBTC_FUNDAMENTAL/USD',
        manualOverrideActive: false,
        breakerBaseline: 6304634918459000000n,
      },
    },
  ],
  fetchedAt: 1786883076,
} satisfies KineticRawData;
