// Frozen mainnet snapshot — generated by scripts/capture-fixture.mjs.
//
// DO NOT HAND-EDIT. Regenerate with `pnpm capture:fixture yieldblox`, then re-derive
// the expected values in adapters/snapshot.test.ts. If a factor moved, find out
// why before committing — that is the entire point of this file.
//
// Captured: 2026-08-20T09:36:36.539Z
// At capture time this scored: safetyScore 24 (collateralSafety 52, oracleSafety 0, adminKeySafety 60, liquiditySafety 10, utilizationSafety 0)
//
// `satisfies` is load-bearing: if BlendRawData gains a required field, this file
// stops compiling rather than quietly feeding the adapter a stale shape.

import type { BlendRawData } from '../blend/index.ts';

export const yieldbloxMainnet = {
  poolId: 'CCCCIQSDILITHMM7PBSLVDT5MISSY7R26MNZXCX4H7J5JQ5FPIYOGYFS',
  oracleId: 'CD74A3C54EKUVEGUC6WNTUPOTHB624WFKXN3IYTFJGX3EHXDXHCYMXXR',
  oracleDecimals: 7,
  status: 0,
  minCollateral: 50000000n,
  admin: {
    address: 'CANSYFVMIP7JVYEZQ463Y2I2VLEVNLDJJ4QNZTDBGLOOGKURPTW4A6FQ',
    isContract: true,
    account: null,
  },
  oracleConfig: {
    maxAge: 900,
    baseAssets: [
      'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75',
      'CB226ZOEYXTBPD3QEGABTJYSKZVBP2PASEISLG3SBMTN5CE4QZUVZ3CE',
      'CCCRWH6Q3FNP3I2I57BDLM5AFAT7O6OF6GKQOC6SSJNDAVRZ57SPHGU2',
    ],
    oracles: [
      {
        index: 0,
        address: 'CALI2BYU2JE6WVRUFYTS6MSBNEHGJ35P4AVCZYF3B6QOE3QKOB2PLE6M',
        resolution: 300,
        decimals: 14,
      },
    ],
  },
  reserves: [
    {
      asset: 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA',
      config: {
        decimals: 7,
        cFactor: 7500000n,
        lFactor: 7500000n,
        util: 5000000n,
        maxUtil: 7000000n,
        enabled: true,
      },
      data: {
        dRate: 1004429084635n,
        bRate: 475605876856n,
        bSupply: 51110737759183n,
        dSupply: 5858753007136n,
      },
      price: { value: 1760719n, timestamp: 1787218200 },
      priceConfig: {
        upstreamAsset: 'Stellar:CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA',
        oracleIndex: 0,
        maxDev: 0,
      },
    },
    {
      asset: 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75',
      config: {
        decimals: 7,
        cFactor: 9500000n,
        lFactor: 9500000n,
        util: 8000000n,
        maxUtil: 9500000n,
        enabled: true,
      },
      data: {
        dRate: 1196832774372n,
        bRate: 969039001613n,
        bSupply: 8686540961571n,
        dSupply: 5781278559824n,
      },
      price: { value: 10000000n, timestamp: 1787218580 },
      priceConfig: null,
    },
    {
      asset: 'CDTKPWPLOURQA2SGTKTUQOWRCBZEORB4BWBOMJ3D3ZTQQSGE5F6JBQLV',
      config: {
        decimals: 7,
        cFactor: 0n,
        lFactor: 9000000n,
        util: 7500000n,
        maxUtil: 9000000n,
        enabled: true,
      },
      data: {
        dRate: 1152500798118n,
        bRate: 1058112475161n,
        bSupply: 8898454621n,
        dSupply: 7360523121n,
      },
      price: { value: 11649341n, timestamp: 1787218200 },
      priceConfig: {
        upstreamAsset: 'Stellar:CDTKPWPLOURQA2SGTKTUQOWRCBZEORB4BWBOMJ3D3ZTQQSGE5F6JBQLV',
        oracleIndex: 0,
        maxDev: 10,
      },
    },
    {
      asset: 'CAUIKL3IYGMERDRUN6YSCLWVAKIFG5Q4YJHUKM4S4NJZQIA3BAS6OJPK',
      config: {
        decimals: 7,
        cFactor: 0n,
        lFactor: 5000000n,
        util: 4000000n,
        maxUtil: 7000000n,
        enabled: true,
      },
      data: {
        dRate: 1032054252218n,
        bRate: 1011145309365n,
        bSupply: 120015695491709n,
        dSupply: 58299241322983n,
      },
      price: { value: 3497n, timestamp: 1787218200 },
      priceConfig: {
        upstreamAsset: 'Stellar:CAUIKL3IYGMERDRUN6YSCLWVAKIFG5Q4YJHUKM4S4NJZQIA3BAS6OJPK',
        oracleIndex: 0,
        maxDev: 0,
      },
    },
    {
      asset: 'CB226ZOEYXTBPD3QEGABTJYSKZVBP2PASEISLG3SBMTN5CE4QZUVZ3CE',
      config: {
        decimals: 7,
        cFactor: 0n,
        lFactor: 9000000n,
        util: 7500000n,
        maxUtil: 9000000n,
        enabled: true,
      },
      data: {
        dRate: 1309580113386n,
        bRate: 1211897040106n,
        bSupply: 5603729634n,
        dSupply: 4667162378n,
      },
      price: { value: 10000000n, timestamp: 1787218586 },
      priceConfig: null,
    },
    {
      asset: 'CBLV4ATSIWU67CFSQU2NVRKINQIKUZ2ODSZBUJTJ43VJVRSBTZYOPNUR',
      config: {
        decimals: 7,
        cFactor: 0n,
        lFactor: 9000000n,
        util: 5000000n,
        maxUtil: 8000000n,
        enabled: true,
      },
      data: {
        dRate: 1057380715248n,
        bRate: 1026286205049n,
        bSupply: 358328674n,
        dSupply: 2618491n,
      },
      price: { value: 10732658n, timestamp: 1787218200 },
      priceConfig: {
        upstreamAsset: 'Stellar:CBLV4ATSIWU67CFSQU2NVRKINQIKUZ2ODSZBUJTJ43VJVRSBTZYOPNUR',
        oracleIndex: 0,
        maxDev: 10,
      },
    },
    {
      asset: 'CAL6ER2TI6CTRAY6BFXWNWA7WTYXUXTQCHUBCIBU5O6KM3HJFG6Z6VXV',
      config: {
        decimals: 7,
        cFactor: 0n,
        lFactor: 8000000n,
        util: 5000000n,
        maxUtil: 8000000n,
        enabled: true,
      },
      data: {
        dRate: 1359978178850n,
        bRate: 1163123190625n,
        bSupply: 272693796906n,
        dSupply: 77226619947n,
      },
      price: { value: 693273n, timestamp: 1787218200 },
      priceConfig: {
        upstreamAsset: 'Stellar:CAL6ER2TI6CTRAY6BFXWNWA7WTYXUXTQCHUBCIBU5O6KM3HJFG6Z6VXV',
        oracleIndex: 0,
        maxDev: 10,
      },
    },
    {
      asset: 'CCCRWH6Q3FNP3I2I57BDLM5AFAT7O6OF6GKQOC6SSJNDAVRZ57SPHGU2',
      config: {
        decimals: 7,
        cFactor: 9000000n,
        lFactor: 9000000n,
        util: 7500000n,
        maxUtil: 9000000n,
        enabled: true,
      },
      data: {
        dRate: 1044984359381n,
        bRate: 1031064277660n,
        bSupply: 10599432633n,
        dSupply: 8334726554n,
      },
      price: { value: 10000000n, timestamp: 1787218591 },
      priceConfig: null,
    },
  ],
  fetchedAt: 1787218596,
} satisfies BlendRawData;
